- README.md
- lua/bufferline.lua
Add mappings which can be toggled on and off via config, for moving to specific buffers.
> Add configurable navigation mappings

- README.md
- lua/bufferline.lua
Right align the tab indicators in the bufferline
> Right align tabs and only show if multiple

- lua/bufferline.lua
- lua/bufferline/config.lua
- lua/bufferline/highlights.lua
This is a subtle change to appease my finickiness, essentially colour of the inactive and current buffers are largely the same with only the text color being different which I think isn't enough. This PR slightly dims the inactive buffer so just a little bit clearer that it isn't the current one
Eagle eyed peeps will notice that the middle buffer is slightly darker than the one on the left but not as dark as the one on the right
> slightly dim the inactive buffer

- README.md
- doc/bufferline-lua.txt
- lua/bufferline.lua
- lua/bufferline/config.lua
Added the ability to make the close button at the far right optional.
> Add option to omit close icon

- README.md
- doc/bufferline-lua.txt
- lua/bufferline/numbers.lua
1. in the new mode 'mix', it will be like lightline-bufferline, with both
ordinal number and buffer id available.
2. number_style will not work in new mode 'mix'
> Added new mode 'both'

- README.md
- doc/bufferline-lua.txt
- lua/bufferline/offset.lua
- tests/offset_spec.lua
Does what it says on the tin 😄
> feat: add ability to align offset text

- lua/bufferline/colors.lua
@Shatur95 can you try this PR to see if it works for you? I didn't/don't notice a difference on my machine so it must be the shade of your colorscheme.
Will fix #107
> Fix: incorrect padding of hex color parts

- README.md
Only opening as a PR so I can preview the markdown properly
> docs: add a table of contents and other minor tweaks

- README.md
- doc/bufferline-lua.txt
- lua/bufferline.lua
- lua/bufferline/duplicates.lua
- tests/bufferline_spec.lua
Adds `CloseBufferLineRight` and `CloseBufferLineLeft` to close all buffers to the right or left of the current buffer.
> feature: add commands to close all buffers in a direction

- README.md
I just found this out of the blue🤣
> fix: Invalid anchor in readme

- lua/bufferline/offset.lua
- tests/offset_spec.lua
> feat: support vertical split window offsets

- autoload/nvim_bufferline.vim
- lua/bufferline.lua
- lua/bufferline/buffers.lua
- lua/bufferline/config.lua
- lua/bufferline/diagnostics.lua
- lua/bufferline/duplicates.lua
- lua/bufferline/numbers.lua
- lua/bufferline/utils.lua
A bit of an arbitrary/?long overdue refactor, that includes some overengineering using function composition to build up the buffer component string. It isn't really necessary, but I like functional programming and the code base is a bit messy, so 🤷🏿‍♂️ .
> refactor: use composition for buffer rendering pipeline

- lua/bufferline/config.lua
@booperlv can you please try this branch and see if it fixes your issue in #220
> fix: convert user config highlights before merging

- lua/bufferline/diagnostics.lua
- lua/bufferline/utils.lua
> fix: use vim.diagnostic.get instead of vim.lsp.diagnostic.get_all

- README.md
- doc/bufferline.txt
- lua/bufferline.lua
- lua/bufferline/buffers.lua
- lua/bufferline/commands.lua
- lua/bufferline/config.lua
- lua/bufferline/constants.lua
- lua/bufferline/custom_area.lua
- lua/bufferline/groups.lua
- lua/bufferline/highlights.lua
- lua/bufferline/models.lua
- lua/bufferline/ui.lua
- lua/bufferline/utils.lua
- tests/groups_spec.lua
- tests/utils.lua
> feat: add pinned groups

- lua/bufferline.lua
- tests/bufferline_spec.lua
- tests/custom_area_spec.lua
- tests/groups_spec.lua
- tests/sorters_spec.lua
- tests/utils.lua
I really don't recall why I thought this would be useful, but delaying the load till after startup is pointless in this case
> refactor: remove delayed loading

- README.md
- doc/bufferline.txt
- lua/bufferline.lua
- lua/bufferline/buffers.lua
- lua/bufferline/commands.lua
- lua/bufferline/config.lua
- lua/bufferline/constants.lua
- lua/bufferline/diagnostics.lua
- lua/bufferline/groups.lua
- lua/bufferline/highlights.lua
- lua/bufferline/models.lua
- lua/bufferline/state.lua
- lua/bufferline/ui.lua
- lua/bufferline/utils.lua
- tests/bufferline_spec.lua
- tests/custom_area_spec.lua
- tests/groups_spec.lua
- tests/sorters_spec.lua
- tests/utils.lua
> Version: 1.1.0

- README.md
- lua/bufferline/config.lua
- lua/bufferline/numbers.lua
- tests/numbers_spec.lua
Remove all code relating to this option
> refactor: deprecate numbers style

- lua/bufferline.lua
- lua/bufferline/utils.lua
> fix: always_show_bufferline should work in tabs mode

- README.md
- doc/bufferline.txt
- lua/bufferline/config.lua
- lua/bufferline/highlights.lua
- lua/bufferline/numbers.lua
- lua/bufferline/ui.lua
- tests/numbers_spec.lua
* Set bufferline highlights as default so plugins can override them (although this is disabled by default)
> Version 1.2.0

- lua/bufferline/config.lua
> fix(config): remove mappings field from defaults

- lua/bufferline/tabpages.lua
It's a bit hacky and I'm not too happy about the solution (calling the filter multiple times), but it accomplishes the goal.
A catch about this solution is that it basically ignores the filter if no buffer in the tab makes it through, not sure if this is desirable or not.
I'm opening this MR now to hopefully get some suggestions on how to improve it so that it can be merged.
Related to #398
> feat(tabpages): add custom_filter

- lua/bufferline.lua
- lua/bufferline/commands.lua
- lua/bufferline/custom_area.lua
- lua/bufferline/groups.lua
- lua/bufferline/highlights.lua
- lua/bufferline/models.lua
- lua/bufferline/ui.lua
- lua/bufferline/utils.lua
* Persist pinned buffers
* Fix custom area highlighting
> version 2.1.0

- doc/bufferline.txt
- lua/bufferline.lua
- lua/bufferline/colors.lua
- lua/bufferline/commands.lua
- lua/bufferline/config.lua
- lua/bufferline/custom_area.lua
- lua/bufferline/diagnostics.lua
- lua/bufferline/duplicates.lua
- lua/bufferline/groups.lua
- lua/bufferline/highlights.lua
- lua/bufferline/models.lua
- lua/bufferline/numbers.lua
- lua/bufferline/pick.lua
- lua/bufferline/sorters.lua
- lua/bufferline/tabpages.lua
- lua/bufferline/ui.lua
- lua/bufferline/utils.lua
- tests/bufferline_spec.lua
- tests/colors_spec.lua
- tests/config_spec.lua
- tests/groups_spec.lua
- tests/ui_spec.lua
- tests/utils.lua
* Add support for cterm
* Refactor internal representation of components
> version: 2.2.0

- README.md
- doc/bufferline.txt
- lua/bufferline.lua
- lua/bufferline/buffers.lua
- lua/bufferline/colors.lua
- lua/bufferline/commands.lua
- lua/bufferline/config.lua
- lua/bufferline/diagnostics.lua
- lua/bufferline/duplicates.lua
- lua/bufferline/groups.lua
- lua/bufferline/highlights.lua
- lua/bufferline/lazy.lua
- lua/bufferline/models.lua
- lua/bufferline/numbers.lua
- lua/bufferline/offset.lua
- lua/bufferline/pick.lua
- lua/bufferline/sorters.lua
- lua/bufferline/state.lua
- lua/bufferline/tabpages.lua
- lua/bufferline/ui.lua
- lua/bufferline/utils.lua
- stylua.toml
* refactor: add ability to disable diagnostic indicator
> version: 2.4.0

- lua/bufferline.lua
- lua/bufferline/colors.lua
- lua/bufferline/commands.lua
- lua/bufferline/config.lua
- lua/bufferline/groups.lua
- lua/bufferline/highlights.lua
- lua/bufferline/models.lua
- lua/bufferline/numbers.lua
- lua/bufferline/offset.lua
- lua/bufferline/pick.lua
- lua/bufferline/sorters.lua
- lua/bufferline/ui.lua
- lua/bufferline/utils.lua
- tests/utils.lua
Fixes a myriad of complaints from the newly updated Sumneko which is now more diligent and frustrating than ever 😄
> chore(lsp): fix annotations for sumneko

- lua/bufferline/utils/init.lua
- related to: https://github.com/akinsho/bufferline.nvim/pull/503#issuecomment-1214373879
> fix: freeze with miniscule truncation values

- .github/release.yaml
Trial automatically generating release notes based on PRs and labels
> ci(github): add release workflow

- lua/bufferline/diagnostics.lua
- lua/bufferline/tabpages.lua
In the same spirit as https://github.com/akinsho/bufferline.nvim/pull/554. This PR combines the diagnostic information shown on the line.
If the same file is open multiple times in the same tab, it is only included once.
> refactor(tabs): diagnostics are the sum of buffer diagnostics

- doc/bufferline.txt
- lua/bufferline.lua
- lua/bufferline/commands.lua
- tests/bufferline_spec.lua
As mentioned here: https://github.com/akinsho/bufferline.nvim/pull/576
> feat(commands)!: reuse close_command for deleting commands

- README.md
- doc/bufferline.txt
See https://github.com/akinsho/bufferline.nvim/pull/592 and https://github.com/akinsho/bufferline.nvim/pull/558
> docs(README): update completed tab PRs

- doc/bufferline.txt
- Add missing comma in groups part
- Add missing quotes in string green
> docs: add missing comma in groups

- doc/bufferline.txt
- lua/bufferline/constants.lua
- lua/bufferline/ui.lua
> Feature: add slope separator 

- lua/bufferline/groups.lua
@NavePnow please test this out and see if it works correctly for you
fixes #687
> fix(groups): clear unpinned buffers from session

- lua/bufferline.lua
- lua/bufferline/groups.lua
Fixes https://github.com/akinsho/bufferline.nvim/issues/692 and https://github.com/akinsho/bufferline.nvim/issues/691
> fix(groups): ensure groups are persisted correctly

- lua/bufferline.lua
- lua/bufferline/groups.lua
fixes: https://github.com/akinsho/bufferline.nvim/issues/695
> fix(groups): only reset the pinned group if it closed

- doc/bufferline.txt
- lua/bufferline/constants.lua
- lua/bufferline/ui.lua
> feat(ui): add `padded_slope` style

- lua/bufferline/groups.lua
- lua/bufferline/ui.lua
- lua/bufferline/utils/init.lua
Some profiling I did recently showed a few methods as being more expensive than I had thought, probably this isn't a night and day improvement but given that it's fixable with a minor tweak 🤷🏾‍♂️
> perf(ui): avoid some expensive functions

- doc/bufferline.txt
> Update `bufferline-functions` documentation

- README.md
removed dual 'LspIndicator' from the toc
> updated the readme: 2 lspIndicators

- lua/bufferline/utils/init.lua
Reverts akinsho/bufferline.nvim#928
> revert: remove fix for referencing unloaded buffers

- lua/bufferline/types.lua
> fix(types): correct mismatched type definitions for sort_by and numbers options
