akinsho/bufferline.nvim

- lua/bufferline.lua
Make each buffer *roughly* the same size. This mirrors the way other GUI editors who buffers, rather than having a tab that is just as long as it's content, this sets each tab to roughly the same size.
This is definitely an opinionated style thing that I think looks better so won't be configurable :upside_down_face:
> Regularise the size of each buffer based on max length

- README.md
- lua/bufferline.lua
- lua/bufferline/config.lua
- lua/bufferline/constants.lua
- lua/bufferline/utils.lua
This change allows a new default whereby if a user sorts buffers into specific positions we maintain the sort order, using `vim.g.variables`. This will require a user to have `sessionopts+=globals` set so session files persist `g` values
> Persist user sorted buffer positions

- README.md
- lua/bufferline.lua
- lua/bufferline/config.lua
- lua/bufferline/highlights.lua
- lua/bufferline/tabs.lua
- lua/bufferline/utils.lua
Highlights are inconsistently named making working with them quite confusing. This PR refactors the naming so it is clearer and more consistent e.g. {item}_{status}, `buffer_visible` etc. It isn't a backward compatible change but I've added in the first part of config validation which checks if a user has any keys in their highlight fields that aren't in the default config aka it is invalid if so we print a message to warn them.
Hopefully people can then check the README to update them
> Improve highlight naming

- lua/bufferline.lua
Recent changes is breaking the plugin for me, the i realized that part was not handling a possible nil prefs obj. That fixed the issue on my side, not sure if its also just something on my side or an actual bug.
My configs are not using any custom prefs in `require('bufferline').setup()` .
> fix nil prefs error

- lua/bufferline.lua
- lua/bufferline/buffers.lua
- lua/bufferline/duplicates.lua
In Windows Terminal, file's icon shows only left part when the buffer is selected. I print the string of the tabline,  finding that the icon's right half is override by other characters.  (The icon I use is two characters width.)  So I make the following changes:
1. Move the white space right before the filename to the position right
after the icon.
2. Insert a white space between the letter when BufferLinePick called.
I use it in both Windows Terminal and vscode's terminal and both work properly.
> Fix rendering problem of file icons in Windows Terminal

- lua/bufferline.lua
Should fix #47. @AnthonyK213 can you try this and see if it fixes your issue?
> Escape percent symbol in filenames

- lua/bufferline/buffers.lua
It looks like initialization of `nvim-web-devicons` is not necessary. Telescope / Lualine also does not initialize `nvim-web-dewicons` manually. Fixes icon colors for me. References #46. Could you please check if this fix breaks icons for you?
> Fix nvim-web-devicons initialization

- doc/bufferline-lua.txt
- lua/bufferline.lua
This PR adds the ability for users to specify colors using the `highlight` name and the part of the highlight to use. for example:
```lua
require("bufferline").setup {
highlights = {
buffer_selected = {
guifg = {highlight = "ErrorMsg", attribute = "fg"},
},
}
}
```
This will use `synIDAttr` and `hlID` to find the value of the `ErrorMsg`'s `fg` color and set the guifg to that value
> Add ability to specify color highlight names

- README.md
- doc/bufferline-lua.txt
- lua/bufferline.lua
- lua/bufferline/buffers.lua
This PR will provide the ability for a user to specify a custom filter function to determine which buffers should not be shown in the bufferline. A user could always do something like `set bufnolisted` etc for a filetype to prevent it from showing up but with a custom filter function they can now do it based on more complex set of circumstances/data.
This is quite similar/relates to #38, cc @cooper-anderson if you are still interested
> Allow users to specify a custom filter function

- README.md
- doc/bufferline-lua.txt
- lua/bufferline.lua
- lua/bufferline/config.lua
- lua/bufferline/highlights.lua
- lua/bufferline/offset.lua
- lua/bufferline/panels.lua
- lua/bufferline/utils.lua
- tests/offset_spec.lua
<details>
</details>
This PR fixes #89 by adding an offset to the bufferline so it begins (and eventually) ends where a sidebar panel starts or ends. This gives the impression that the bufferline is local to the window, similar to GUI editors.
The implementation is based on adding padding/text before or after the bufferline so is somewhat hacky, if this somehow proves problematic in the long term this might need to be revisited +/- deprecated.
NOTE: I am *not* taking more feature requests on top on this functionality, I'm not going to add anything jazzier to this i.e. it will be text or an empty space above the window
> feat: add offset for sidebar windows

- lua/bufferline/buffers.lua
I use nvim-nonicons, which has a few overrides from the original nvim-web-devicons plugins. One of which is terminal, which has the decimal value of [62601](https://github.com/kyazdani42/nvim-web-devicons/blob/1db27380053de0cd4aaabd236a67c52d33199f1a/lua/nvim-web-devicons.lua#L856) in the original plugin, whilst the nonicons plugin has the decimal value of [61911](https://github.com/yamatsum/nvim-nonicons/blob/5056aebb8d0ecc87b26a4f7fe9e9e520e5ea493f/lua/nvim-nonicons/mapping.lua#L216) for the same icon.
This results in a broken glyph, which could also be a result of my bad font patch. Either way, as long as the key is called `"terminal"`, this should fix it.
> Get icon from terminal key

- README.md
- lua/bufferline.lua
- lua/bufferline/custom_area.lua
- tests/custom_area_spec.lua
This will allow a user to specify a custom section on either end of the statusline.
This can be used as
```lua
config = {
options = {
custom_areas = {
left = function()
return {
text = "  " .. vim.lsp.diagnostic.get_count(0, "Error"),
guifg = "salmon",
},
end
}
}
}
```
Fixes #98, cc @weilbith can you give this a try and see if it works for you. I really don't want to go down any rabbit holes having to add refresh logic or anything so if it doesn't I might have to scrap this.
> feat: add ability to add a custom section

- README.md
- doc/bufferline-lua.txt
- lua/bufferline.lua
- lua/bufferline/constants.lua
- lua/bufferline/utils.lua
This fixes #125 by adding a new style specifically for terminals that required padding for the separator characters. Rather than trying to determine what terminal a user is on (since this is waaaay to brittle, and my initial assumption that kitty was an exception was wrong), the user has to decide which style to use for themselves.
@siduck76 you will need to change your config if you are using `slant` once this PR gets merged. @Racle can you see if this fixes the issue for you.
> fix: add padded slant style for some terminals

- README.md
The given custom area example is working in general, but only if all 4 lsp diagnostics are greater than zero. It does not show the right area when only infos are present, for example.
This PR updates the readme to show an example of a custom area that will shown any hint. Note the replacement of `result[0] = ` with `table.insert`. This configuration fixed it for me.
> update readme with more generic custom area example [closes #128]

- README.md
- doc/bufferline-lua.txt
- lua/bufferline.lua
- lua/bufferline/buffers.lua
- lua/bufferline/config.lua
- tests/bufferline_spec.lua
This PR adds the ability to format the name a buffer is given in the bufferline. It is intended to potentially make otherwise confusing names clearer or for minor tweaks to naming.
It is not intended as a way for users to use full paths as names or inject highlighting etc. If users use it for such it will break, and I will not fix that 🤷🏾‍♂️ .
The key can be specified as
```lua
--- NOTE that if nil is returned the default will be used anyway
name_formatter = function(default_name, path)
if condition then
return <new-name>
end
end
```
> feature: add name formatter

- README.md
the setting should be `sessionoptions` not `sessionopts`, atleast on neovim 0.5.0. 
I don't have vim installed to check but googling seems to show its sessionoptions there too
> Typo in README.md s/sessionopts/sessionoptions/

- lua/bufferline.lua
- lua/bufferline/config.lua
- lua/bufferline/utils.lua
- tests/bufferline_spec.lua
- tests/config_spec.lua
This PR moves the most expensive parts of the startup logic to a separate function `__load()` to be called after nvim has started. As well as reducing the amount of modules required at startup. This reduces the startup time of the plugin. Not sure yet if this is an unnecessary optimisation, but I'd rather this plugin was as inexpensive to load as possible.
If anyone sees this and wants to try it out, please let me know if it breaks any behaviour. I intend to try it out myself for the next couple of days and merge it if I don't find any issues.
> refactor: defer startup

- lua/bufferline.lua
This PR changes startup to only show the bufferline on startup if a user has configured it to show up
@Pocco81 please try this to see if it fixes the issue.
> fix: hide bufferline on start if not configured

- README.md
- doc/bufferline-lua.txt
- lua/bufferline.lua
This commit adds the functionality requested in #150. Namely,  a command to pick a buffer and close it (similar to BufferLinePick but closes instead of selects). I've also refactored bufferline.pick_buffer() so that both it and the new bufferline.close_buffer() can share the same logic. I've refrained from adding anything to README.md as my writing style would probably clash with @akinsho 's. Also my color scheme is a bit different so pictures would look out of place. I've tried adding a test or two but I couldn't find any tests for bufferline.pick_buffer(), so I could not figure out how to give user input in code.
P.S. this is my first pull request ever, please be gentle.
> feature: add command to select and close a buffer

- README.md
Hi, a little PR to fix the Vimscript usage in the README:
* The vimscript comment must be outside the lua heredoc, otherwise it triggers an error
* No `lua` keyword required before the `require()` (also triggers an error)
> Fix Vimscript usage in README

- lua/bufferline.lua
- lua/bufferline/utils.lua
I saw this TODO in the code and thought I could do something about it. The original implementation took quadratic time (O(|sorted|*|buf_nums|)). This one is linear. This makes use of a utility function tbl_reverse_lookup, which is similar to vim.tbl_add_reverse_lookup, except that this one creates a new table instead of modifying the original (this is necessary because the both the keys and the values are numerical, so you can't exchange in place). This implementation reorders buf_nums in place. I've checked the references and they're all in the form of "buf_nums =  get_updated_buffers(buf_nums, sorted)", so I assume it's fine to do it in place. If not, I'm not sure exactly how to shallow copy buf_nums ellegantly (i.e. without a loop) as table.unpack is now depreciated and I'm not sure if …
> Refactor: improve get_updated_buffers

- lua/bufferline.lua
This PR adds trunctation of multibyte strings by cell/column rather than by byte, only if the byte count of a string does not match display size i.e. if it contains multibyte characters
@alohaia can you try this PR and see if it fixes #177
> fix: truncate multibyte characters by cell

- README.md
- doc/bufferline-lua.txt
- lua/bufferline.lua
- lua/bufferline/buffers.lua
- lua/bufferline/config.lua
- lua/bufferline/utils.lua
This PR adds the ability to operate on bufferline buffers based on their visual position in the bufferline rather than their absolute position
```lua
require'bufferline'.buf_exec(
4, -- the forth visible buffer from the left
user_function -- an arbitrary user function which gets passed the buffer
)
-- e.g.
require'bufferline'.buf_exec(2, function(buf)
vim.cmd('bdelete '..buf.id)
end
```
This also refactors the `<leader>0-9` mappings to operate on the visible buffers rather than their absolute positions in the list so 2 will open the 3rd visible buffer in a hypothetical list of 20 not necessarily the 2nd which might not be currently visible
> feat: execute user function against visible buffers

- doc/bufferline.txt
Hey, hope you're doing well!
It took a few days for me to update by setup to match the recent "breaking changes" and I noticed that there was an inconsistency in the Numbers section of the docs while updating my configs so this PR aims to fix it.
Regards
> fix(docs): correct name for buffer id on numbers section

- lua/bufferline/offset.lua
When `:h 'winhl'` contains multiple entries for the same hl-group, vim will
use the last one. Thus, we should search the winhl entries in reverse
order when we are trying to guess the offset hl.
Example:
- The value of `'winhl'` is `Normal:Foo,Normal:Bar,Normal:Baz`.
- Vim will in this case link `Normal` to `Baz`, but the current implementation will guess `Foo`.
> fix(offset): Search winhl in reverse order when guessing hl.

- lua/bufferline.lua
- lua/bufferline/config.lua
- lua/bufferline/diagnostics.lua
Looks like hint level diagnostics are not explicitly set to derive hl from corresponding existing groups, so I did that. Not sure about the fallback, seems suitable though.
> feat: Add hint diagnostic highlight

- lua/bufferline/diagnostics.lua
This should fix #285 . Instead of checking 0.7 nightly, now just check if the version is greater than 0.6.1.
> fix: 0.6.1 diagnostic deprecation warning #285

- lua/bufferline/numbers.lua
Small buffer index padding fix - if `numbers` is a function that returns an empty string we don't need additional padding.
I am using it in the following example 
```
numbers = function(opts)                                         
if vim.api.nvim_get_current_buf() == opts.id then return "" end
return opts.ordinal                                            
end,                                                             
```
Before - extra padding
After - no extra padding
> chore: no extra padding if numbers func returns empty string

- doc/bufferline.txt
- highlight groups, under the "HIGHLIGHTS"
section, had inconsistent quoting, e.g.
guifg = <color-value-here> versus
guifg = '<color-value-here>'. All
quoting in example highlight groups should
now be fixed
> docs: fix inconsistent highlight group quoting

- lua/bufferline.lua
- lua/bufferline/colors.lua
This makes the dependency explicit, limits the scope to the current file and provides faster access to the bit.* functions, too. It's good programming practice not to rely on the global variable bit being set (assuming some other part of your application has already loaded the module). The require function ensures the module is only loaded once, in any case.
Without explicit adding the line I receive:
```
lua/bufferline/colors.lua:71: attempt to index global 'bit' (a nil value)
```
> refactor: explicitly require the bit module

- lua/bufferline/diagnostics.lua
Coc will trigger `CocDiagnosticChange` when diagnostic status changed.
Only get diagnostics when `CocDiagnosticChange`, can avoid a lot of
unnecessary `CocActionAsync` calls.
> perf(coc-diagnostics): use event `CocDiagnosticChange`

- lua/bufferline.lua
- lua/bufferline/buffers.lua
- lua/bufferline/commands.lua
- lua/bufferline/config.lua
- lua/bufferline/set.lua
- lua/bufferline/sorters.lua
- lua/bufferline/state.lua
This refactors the *buffer* handling to use an ordered set to maintain internal buffer state, rather than just directly reproducing the list we get from nvim. With more control, we can now add buffers at specific points in the list
Fixes #232
> feat: insert new buffers after current

- lua/bufferline/models.lua
fix: missing visibility method on TabPage
Added missing method for TabPages.
See: #353
> fix: missing visibility method on TabPage

- lua/bufferline.lua
- lua/bufferline/utils.lua
This was due to state not being populated correctly, so the list of open buffers gets one step out of sync
fixes #352
> Fix: don't cycle to closed buffers if showtabline is 0

- README.md
- doc/bufferline.txt
- lua/bufferline/config.lua
- lua/bufferline/constants.lua
- lua/bufferline/diagnostics.lua
- lua/bufferline/models.lua
- lua/bufferline/utils.lua
- tests/bufferline_spec.lua
`nvim-web devicons` allows users to specify if they would like to see default icons or not in their setup, i.e. 
```lua
require('nvim-web-devicons').setup {
default = true | false
}
```
This plugin has historically ignored this and always used a default icon for consistency. I personally detest the inconsistency of some buffers having icons and some not. Anyway, it's a little annoying for the user that they can't override this despite maybe having expressed a preference in nvim devicons so this PR allows them to disable the default icon via this plugin's config.
I think it's a little strange to have another plugin decide if this plugin shows default icons or not and most importantly, if this was set globally via nvim web devicons then it wouldn't be possible to have specific behaviour …
> refactor: allow setting default icon state

- doc/bufferline.txt
- lua/bufferline/config.lua
- lua/bufferline/highlights.lua
This PR will fix #320 by allowing a user to set a config option, currently `themable` which will allow highlights created by bufferline to be `default` i.e. more easily overridden by colorschemes.
It's really important to understand that by default bufferline is not intended to be themed by colorscheme authors, it was designed to derive a palette based on common highlight groups which are generally set in most colorschemes. So changing individual highlights is not advisable, but since there is some demand amongst colorscheme authors, this change will make this possible. However, I *strongly* recommend against it since the highlights are derived dynamically and so the names can change, breaking colorschemes highlights.
In general, it would be better for colorschemes to ensure all the basic …
> feat(config): add themeable option

- lua/bufferline/config.lua
- lua/bufferline/highlights.lua
- lua/bufferline/numbers.lua
- lua/bufferline/ui.lua
Adds the ability to highlight the numbers component, by default these are not highlighted.
fixes #280 
Caveat:
You cannot highlight subcomponents directly as that would be a pain to implement and a lot of complexity with insufficient value IMO
> feat(config): add numbers highlight

- .github/workflows/formatting.yaml
- .github/workflows/test.yaml
I'm unsure but I would guess the primary branch for bufferline changed very recently- it happened to break my nvim config when I updated today (because of how packer handles branches) and as I was poking around trying to figure out what happened I noticed these two files still referencing master.
(PS: thanks for the great plugin!)
> CI: update github workflow (use main branch)

- README.md
- lua/bufferline.lua
There seems to have been a few changes to the API that did not get documented in the README.  Wasn't too hard to reverse engineer, so when I figured it out I changed the README to reflect what I found.
> fix: correctly re-export and document exec function

- .github/workflows/test.yaml
- README.md
- lua/bufferline.lua
- lua/bufferline/highlights.lua
- lua/bufferline/utils.lua
With nvim 0.7 now being stable, this plugin is migrating all the pre-0.7 hacks
for autocommands, commands and highlights to the new apis that allow these things to be done natively in lua
> BREAKING: switch to 0.7 api functions

- lua/bufferline/groups.lua
If a user has specified the pinned builtin then priority should be taken from the list's order, otherwise all the groups should have their priorities adjusted by 1
fixes #376
> fix(groups): assign priority based on if pinned specified

- lua/bufferline/duplicates.lua
> fix(duplicates): use utils.truncate_name to truncate ancestors

- lua/bufferline/custom_area.lua
- lua/bufferline/highlights.lua
Unless there is a local preference,
this should fix @siduck's issue, but might break @jjc224 @denstiny issues again. Can you all test, please? It's probably most important that @denstiny and @jjc224's issues are fixed since this is the normal/advised usage of this component, so that should work. @siduck's usage is not recommended, so might not be fixable
> refactor: use themable for all highlight settings

- README.md
For Windows users like me, who didn't know, that there is a distinct config file for disabling the GUI Tabline in Neovim. Took me a while to figure this one out. 😅
> docs(README): add a note for GUI users to the FAQ.

- lua/bufferline/highlights.lua
This change allows users to directly set the value of `underline`, `undercurl`, `bold`, `italic` etc. rather than relying on `gui` exclusively
fixes #431
> fix(highlights): allow setting GUI attributes to NONE

- lua/bufferline/highlights.lua
- lua/bufferline/ui.lua
Don't use `fg` for cterm colours since this will break if no colour was set for the cterm of a theme or more specifically for the Normal hl group
@rudotriton does this PR fix your issue, will probably break stuff for someone else 🤷🏿 
fixes #433
> fix(highlights): only set cterm values if not termguicolors

- lua/bufferline/ui.lua
Explicitly convert the text attribute of each segment to string when calculating the component size. Some values can be numbers.
```
{
highlight = "BufferLineBackground",
text = "config.go"
}
{
text = " "
}
{
highlight = "BufferLineSeparator",
text = "▕"
}
{
highlight = "BufferLineBackground",
text = " "
}
{
highlight = "BufferLineBackground",
text = " "
}
{
attr = {
__id = "number"
},
highlight = "BufferLineNumbers",
text = 1
}
```
> fix(tabs): explicitly convert segments text attribute to string

- lua/bufferline/highlights.lua
- lua/bufferline/ui.lua
* Fixes incorrect truncation behaviour
* Gate setting cterm values if a user is not using termguicolors
* Fix text for each component not being converted to a string before being counted
> version 2.2.1

- lua/bufferline/models.lua
Works :)
Config used:
```lua
require("bufferline").setup {
options = {
mode = "tabs",
close_command = "tabclose",
right_mouse_command = "tabclose",
left_mouse_command = "tabnew %d",
offsets = {
{
filetype = "NvimTree",
text = "",
padding = 1,
},
},
name_formatter = function(tab)  -- tab contains a "name", "path" and "tabnr"
return string.format("name = %s, path = %s, tabnr = %d", tab.name, tab.path, tab.tabnr)
end,
buffer_close_icon = "",
modified_icon = "",
close_icon = "",
show_close_icon = false,
left_trunc_marker = "",
right_trunc_marker = "",
max_name_length = 100,
max_prefix_length = 13,
tab_size = 20,
show_tab_indicators = true,
enforce_regular_tabs = false,
view = "multiwindow",
show_buffer_close_icons = true,
separator_style = "thin",
always_show_bufferline = true, …
```
> feat(tabpages): add name_formatter

- README.md
- doc/bufferline.txt
- lua/bufferline/diagnostics.lua
- lua/bufferline/ui.lua
Supersedes #459 and fixes #452
> refactor(ui): allow diagnostics to be empty

- lua/bufferline/commands.lua
- lua/bufferline/config.lua
Hey, you might remember me working on tabpage filtering a while ago.
Since then I've discovered a bug where basically bufferline tried to close tabpages using the tabpage handle instead of the tabpagenr.
I finally got the time to find the code responsible for this and fix it! As you can see it was fortunately a very simple fix.
> fix(tabpages): use tabpagenr for closing tabpages

- README.md
- doc/bufferline.txt
- lua/bufferline/commands.lua
Allows to open the buffer in the last visible `go_to_buffer(-1)` or absolute `go_to_buffer(-1, true)`  position.
To keep it light, no further commands were added.
If you like this PR to be extended by adding such commands please feel free to extend it or let me know how I can help.
> feat: go_to_buffer(-1) opens last buffer

- lua/bufferline/config.lua
This PR will allow passing the default highlights to a specified highlight function in the config so a user can tweak the highlights based on the derived defaults
> refactor(config): allow highlights to be a function

- doc/bufferline.txt
Had an occasional highlight that didn't played along and couldn't figure out whats wrong as it was missing in the help docs. 
Let us make the `hint`-group as easy accessible as the other ones 😊
> docs(bufferline.txt): add missing hint highlights

- lua/bufferline/models.lua
- lua/bufferline/tabpages.lua
This implements unique names for tabpages.
I looked around for documentation to update, but I don't see anything to change. The feature will just work now for tabs like it does and is described for buffers.
**Here is a screenshot of some unique tabs:**
- _hammerspoon/init.lua_
- _config/nvim/init.lua_
- _config/nvim/lua/wassim/cmp/init.lua_
**For clarity, here is my current config:**
``` lua
require('bufferline').setup({
options = {
mode = 'tabs',
show_buffer_close_icons = true,
show_close_icon = false,
always_show_bufferline = false,
separator_style = 'slant',
enforce_regular_tabs = false,
offsets = {
{
filetype = 'NvimTree',
text = nil,
},
},
},
})
```
Closes https://github.com/akinsho/bufferline.nvim/issues/430.
> feat(tabpages): support unique tab names

- lua/bufferline/commands.lua
When a user has hidden the tabline this fallback allows cycling with the normal bnext and bprev commands
@Pocco81 can you test this out to see if it works for you.
fixes #488
> feat(commands): fallback to b{prev|next} when cycling buffers

- lua/bufferline.lua
- lua/bufferline/duplicates.lua
- lua/bufferline/groups.lua
- lua/bufferline/models.lua
- lua/bufferline/tabpages.lua
- lua/bufferline/utils/init.lua
- tests/duplicates_spec.lua
When deduplicating tabpages it is possible for the same buffer to appear twice. Previously that forced the function handling deduplication to exit early, so tabs would not appear in the tabline. This PR changes that function to mark an element as being an exact match to another, which is only relevant for tabs. This way, tabs can have a special indicator to show that a tabs buffer is the same as another.
fixes #500
> feat(duplicates): handle identical buffers

- lua/bufferline/constants.lua
- lua/bufferline/offset.lua
- lua/bufferline/utils/init.lua
- tests/offset_spec.lua
- tests/utils_spec.lua
This PR fixes #495 
@tobealive can you please try this PR out. It uses the utility function I mentioned to truncate the offset text specified, whether it includes multibyte characters. The issue you were having with that function comes down to the fact that the text was being changed to try and remove the extension, but this was initially intended for use with buffer names with extensions, so it ended up changing the text if using a directory, but that should be fixed now
> fix(offset): truncate long offset text with multibyte characters

- doc/bufferline.txt
I noticed the following highlight groups are not documented: `numbers`, `numbers_visible` and `numbers_selected`. I had to look in the code to realize they exist. I believe it can be useful for other users to have them in the docs.
> Document highlight groups for bufferline tab numbers

- doc/bufferline.txt
* I found this while looking at the documentation. It's a tiny typo.
> fix(docs): tiny typo

- doc/bufferline.txt
- lua/bufferline/config.lua
- lua/bufferline/constants.lua
- lua/bufferline/tabpages.lua
- lua/bufferline/ui.lua
- tests/bufferline_spec.lua
- tests/config_spec.lua
- tests/ui_spec.lua
- tests/utils.lua
This PR refactors the `indicator_icon` to be a table called `indicator` which allows now specifying a `style` +/- and `icon`. The only alternative style other than an icon is an underline, which now allows the following appearance. Obviously, a user's mileage will vary depending on their terminal emulator of choice and how it draws underlines.
This is using `kitty` with the underline thickness increased to `150%`
> feat(config)!: add underline indicator style

- doc/bufferline.txt
- lua/bufferline/config.lua
- lua/bufferline/offset.lua
This PR allows offsets to have a separator which appears similar to the vertical separator vim uses. This can be used to give the appearance of a complete vertical separator when using bufferline with offsets.
> feat(offset): add optional offset win separator

- lua/bufferline/utils/init.lua
`vim.loop.os_uname()` output:
```
{
machine = "x86_64",
release = "10.0.19044",
sysname = "Windows_NT",
version = "Windows 10 Enterprise"
}
```
'Side-effect' of this is that path separator might look like pipe with some fonts (because of italics) now.
> fix(utils): improve path separator detection on windows

- doc/bufferline.txt
In updating my config for the new indicator icon settings I was getting an error after copy and pasting from the docs. I noticed it was because of a missing comma in the docs.
> docs(help): add missing comma to indicator config

- doc/bufferline.txt
- lua/bufferline/config.lua
- lua/bufferline/ui.lua
- lua/bufferline/utils/init.lua
- tests/ui_spec.lua
This fixes #532 by allowing a user to set `autosize = true` in `config.options`. With this enabled, users can allow filename to extend up to their full name length.
Can you test this out @ray-x, I might change the option name in future commits since I'm not sure I like `autosize` it's really not very descriptive.
> feat: add option to disable name truncation

- lua/bufferline/custom_area.lua
- tests/custom_area_spec.lua
Hi there!
This PR fixes a minor bug introduced with https://github.com/akinsho/bufferline.nvim/pull/497 that prevents the default fill background from being used in custom areas.
I've also updated the references in the test, but I couldn't figure out how to run the tests, so I hope it's okay :woman_shrugging:
Thanks for the fantastic plugin!
> fix: custom area background highlight

- lua/bufferline/models.lua
If a buffer is modified within a tab, the tab is only marked as modified if that buffer is in focus. This PR marks the tab as modified if any of the buffers in the tab are modified.
> refactor(tabs): tab is modified if any child buffer is modified

- doc/bufferline.txt
- lua/bufferline/config.lua
- lua/bufferline/duplicates.lua
Added a boolean option to enable or disable duplicate buffer prefix.
> feat(duplicates): toggle unique buffer name (#469)

- lua/bufferline/commands.lua
Hi! I made a PR to fix the bufferline not redrawing after calling `close_in_direction` from a keybinding :)
This will fix #586
> fix(commands): trigger redraw after delete in direction

- lua/bufferline/buffers.lua
- lua/bufferline/tabpages.lua
- lua/bufferline/utils/init.lua
Before this PR, when in tab mode, the commands `BufferLineMoveNext` or `BufferLineMovePrev` did not visually change any tab positionings in the UI. Now it will update in the UI.
https://user-images.githubusercontent.com/52012721/196027505-feeac011-3cfe-4773-a031-dc9ff742fcf7.mov
https://user-images.githubusercontent.com/52012721/196027539-84d08805-0af8-4f7c-b04a-48e538780389.mov
> feat(tabs): allow moving/reordering tabs

- lua/bufferline/buffers.lua
- lua/bufferline/tabpages.lua
- lua/bufferline/utils/init.lua
This reverts commit b4db22d86fcc08e774b6208d0eb8bd59fc521bb0.
See discussion here: https://github.com/akinsho/bufferline.nvim/pull/588#issuecomment-1282145111
> revert(tabs): allow moving/reordering tabs (#588)

- lua/bufferline/config.lua
- lua/bufferline/sorters.lua
Bufferline currently sorts tabs by id (neovim internal handle) instead of my number (vim user sorted tabpages). Bufferlines `sort_by_tabs` already properly sorts this. This PR applies `sort_by_tabs` by default for tab users.
> feat(tabs): sort by tab number instead of tab id

- lua/bufferline/tabpages.lua
In tabs mode, unnamed buffers do not have any name appear in the tabline. This is in contrast to buffers mode, where they appear as "No Name." It seems the infrastructure to do this was implemented, but it didn't work due to a logic error caused by the assumption that the empty string is treated as falsy in Lua.
> fix(tabs): show unnamed buffers

- lua/bufferline/hover.lua
There is not really a point in gatekeeping this feature from `laststatus=0`.
The hover feature works completely fine with `laststatus=0` and this creates only problems with other plugins, see: https://github.com/vimpostor/vim-tpipeline/issues/39
> fix(hover): check showtabline not laststatus

- doc/bufferline.txt
Noticed a comma was missing when I was looking through the docs, so I added it :)
> docs(bufferline.txt): add missing comma to docs

- doc/bufferline.txt
- lua/bufferline/ui.lua
The tab close icon can look a little odd (and won't do anything) if there's only one tab in use. See [this reddit post ](https://www.reddit.com/r/neovim/comments/v9211b/can_we_remove_the_x_on_the_right_side_of_the/)
Since I would guess many people who use this plugin would be less inclined to use standard vim tabs - I thought it would make sense and improve aesthetics to remove it if there's only one tab in use (it will reappear if the user opens another tab). For those who want to always see the tab close icon, the `always_show_tab_close_icon` option can be set to `true` in setup (default is `false`). 
Please let me know your thought and btw I love this plugin :)
> refactor(tabs): only show close icon if multiple tabse

- doc/bufferline.txt
The syntax was wrong, I fixed it.
> docs(help): add a missing comma

- doc/bufferline.txt
- lua/bufferline/config.lua
Adds missing types to config fields.
Though in case of the separator style id did just a quick scan through the code base, I can not 100% verify if the string dict is the right union type . But it seemed fine to me.
> docs: update config type annotations

- lua/bufferline/groups.lua
Fixes https://github.com/akinsho/bufferline.nvim/issues/678
> fix(group): check that group exists before operating on it

- doc/bufferline.txt
- lua/bufferline.lua
- lua/bufferline/commands.lua
I added a `move_to` function and `BufferLineMoveTo{First|Last}` commands so one can easily move the current buffer to the `n`-th position in the bufferline.
It's a bit like `:tabmove` but for buffers.
`move_to` takes an 1-based buffer index. Negative integers are allowed but 0 is ignored.
---
P.S. This is an awesome project! Thank you to all the maintainers for putting in so much time and effort to make this possible. I'm really enjoying using it and I'm so grateful for all the work that went into it. Keep up the great work!"
> feat: allow moving buffers to arbitrary positions

- doc/bufferline.txt
- lua/bufferline/config.lua
- lua/bufferline/utils/init.lua
- tests/bufferline_spec.lua
Since there have been many requests to have icons fetch in some way that a user might prefer e.g. with defaults without defaults, by filetype, by filename, maybe eventually by different package than devicons, this PR adds a `get_icon_element` option which a user can use to decide what is return for each element which is essentially a filename, filetype, directory and path.
cc @camiloaromero23 @utilyre @CleoMenezesJr
I've closed #669 in favour of this change since that continues us down the path of option after option of `load_by_x_criteria`. This way a user can just explicitly do whatever they want.
Can you please test this PR to see if
a) It solves the original issue
b) It correctly allows you to return whatever icon you want
> feat(icons): add `get_element_icon` option

- lua/bufferline/utils/init.lua
https://github.com/akinsho/bufferline.nvim/pull/726 Introduced a bug because `utils.is_list` need to be executed in order to return a function that will return a boolean if the object is a list. This broke the tests, now it properly returns a `boolean`.
I ran the tests with the following command I got from the ci workflow yaml.
```sh
nvim --headless -u tests/minimal_init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/minimal_init.lua', sequential = true}"
```
I also ran the formatter with:
```sh
stylua --config-path=stylua.toml lua/
```
> fix(utils): fix utils.is_list

- lua/bufferline/colors.lua
- lua/bufferline/config.lua
**tl;dr** To support colorschemes where LSP diagnostics are highlighted with colored underlines instead of foreground text (see screenshot below), check whether the `special` attribute exists before using the fallback group.
Result, here with an error diagnostic:
---
My main motivation is to allow a sensible fallback to the <ins>underline</ins> color in case any of the `DiagnosticError`, `DiagnosticWarn`, `DiagnosticHint` or `DiagnosticInfo` highlight groups do not have a foreground color set.
In many IDEs, it is a [common practice](https://user-images.githubusercontent.com/7727148/38758132-7284e58a-3f24-11e8-8e39-627e6916e9ec.PNG) to highlight diagnostics by underlining the context, instead of changing its foreground color. Due to Vim's legacy of supporting terminals without capabilities …
> feat(diag): sane fallback to underline color

- doc/bufferline.txt
In 83b4d0b, the default `buffer_close_icon` was updated to reflect the breaking changes in Nerd Fonts, however the documentation was not updated to use this new default in its example config. This PR updates that to make them consistent.
> docs(help): update buffer_close_icon

- lua/bufferline/utils/init.lua
Makes consistent use of the strwidth helper var declared at the top of the file.
Simple refactor. No real work done here.
Great work with the plugin, I like the performance especially. Thanks a lot for providing value @akinsho.
> refactor(utils): use helper variable consistently

- lua/bufferline/commands.lua
This is how tabs work in most apps (at least on macOS).
I can put this behind a config option if required.
> feat(commands/go_to): go to the last element if index out of bounds

- doc/bufferline.txt
Add commas in some examples so that users can copy them directly without having errors like
```lua
fg = '<colour-value-here>',
bg = '<colour-value-here>',
sp = '<colour-value-here>'  -- missing a comma here
bold = true,
italic = true,
```
> docs: fix commas in highlights examples

- lua/bufferline.lua
- lua/bufferline/commands.lua
- lua/bufferline/state.lua
- lua/bufferline/types.lua
- lua/bufferline/utils/init.lua
- tests/utils_spec.lua
This fixes an issue where restoring the custom sort order from a saved session doesn't work correctly most of the time, because it stores buffer ids in `g:BufferlinePositions` which are not preserved by `:mksession`. The fix is to store the full paths of the buffers instead. `vim.json` is required to stringify the list as `:mksession` only stores string/number values.
Split out from #777.
> fix: store paths in g:BufferlinePositions

- lua/bufferline/config.lua
This PR fixes a bug introduced in [this commit](https://github.com/akinsho/bufferline.nvim/commit/13cb114e91c17238aaa271746aaeb8e967f350a2) in `lua/bufferline/config.lua` at line 563: `normal_bg` was replaced with `visible_bg` for `tab_separator_selected` background color which is inconsistent with `separator_selected` background color and produces this problem:
> Fix highlighting for tab separators

- doc/bufferline.txt
- lua/bufferline/config.lua
- lua/bufferline/ui.lua
I added a new highlight for the trunc marker, because it was using the `BufferLineFill` hl.
I also updated the docs.
> feat(ui): trunc marker highlights

- lua/bufferline/models.lua
This adds a new config option `unnamed_title` to support changing the name of unnamed buffers from `[No Name]` to anything the user wants (e.g. `Untitled`).
> feat: Support `name_formatter` for unnamed buffers

- lua/bufferline/utils/init.lua
pretty much a fix for #191
normally  `bufferline` retrieves the file extension using `vim.fn.fnamemodify` with the `:e` option, but that doesn't account for extensions with multiple dots, by passing nil instead of that extension, the inner recursive mechanism of `nvim-web-devicons` is utilized to get the longest matching extension from the filename
before:
after:
> fix: display overriden devicons

- lua/bufferline/commands.lua
If one uses this method mapped to keys and accidentally hit a number with a non-existing buffer, `element` can be nil:
```
E5108: Error executing lua: ...re/nvim/lazy/bufferline.nvim/lua/bufferline/commands.lua:122: attempt to index local 'element' (a nil value)
stack traceback:
...re/nvim/lazy/bufferline.nvim/lua/bufferline/commands.lua:122: in function 'go_to'
```
> Fix potential nil access

- lua/bufferline/types.lua
As discussed in the mentioned issue, it appears that some changes to lua_ls mean that not including non-optional fields in a config table throws a diagnostic warning, as shown in the screenshot. As the issue mentions, it's possible to disable this behavior globally or with a `---@diagnostic disable-next-line missing-fields` comment before the table, but I think it would still be greatly desirable to have bufferline not throw warnings for non-mandatory fields by default.
I've tried my best to only make the non-mandatory fields optional, but I probably over or under-modified the types, so please feel free to add/remove `?`s around the types file.
https://github.com/LuaLS/lua-language-server/issues/2214#issuecomment-1686426027
> fix: remove `missing required fields` diagnostic from config

- lua/bufferline/custom_area.lua
fix #838 
If use specified a highlight group via link, use it instead of creating a new group
> use link if specified in custom areas

- lua/bufferline/utils/init.lua
fix #840
Make sure ext is valid before matching it.
> fix: skip invalid regex in truncate_name

- doc/bufferline.txt
- lua/bufferline.lua
- lua/bufferline/commands.lua
- lua/bufferline/tabpages.lua
* Ported over changes from previous PR
> feat(ui): Tab Renaming

- lua/bufferline/types.lua
> fix wrong type for `level` in `diagnosticIndicator`

- lua/bufferline/tabpages.lua
`string` cannot be called directly:
```
attempt to call a table value (global 'string')
```
To convert a number to string in Lua, we need to call `tostring(num)` instead.
> fix a typo in rename_tab

- lua/bufferline/tabpages.lua
vim.fn.tabpagenr gets the tab number but api.nvim_tabpage_set_var expects tab id, meaning the tab rename would fail if a tab was closed and reopened. This change passes 0 into api.nvim_tabpage_set_var which will use the current focused tab without needing to retrieve the id.
Before this change:
https://github.com/akinsho/bufferline.nvim/assets/159239255/d219e828-6997-4bb0-8fda-07a41c58e085
After this change:
https://github.com/akinsho/bufferline.nvim/assets/159239255/0bf298bd-d6d2-438c-9b5f-c3254397e1b0
PS: Thank you for making bufferline!
> fix(tabpages): renaming bug on reopened tab

- doc/bufferline.txt
- lua/bufferline.lua
- lua/bufferline/config.lua
- lua/bufferline/types.lua
Currently, there are no commands for enabling, disabling, or toggling the bufferline. The current way to control the visibility of the tabline (as mentioned in #651 and #829) is to set the `showtabline` option. However, this does not reliably control the visibility of the tabline because bufferline.nvim overwrites this option. 
This PR adds a configuration option called `auto_toggle_bufferline`. When set to `false`, bufferline.nvim will not overwrite the `showtabline` option. This more closely aligns with the default behaviour of the built-in Vim tabline. That is, setting `showtabline` to `0` will hide the tabline, and it will not be reappear unless this option is modified manually. 
To maintain backwards compatibility and avoid breaking existing configurations, `auto_toggle_bufferline` …
> feat: add `auto_toggle_bufferline` option

- lua/bufferline/diagnostics.lua
Avoid getting deprecation warnings.
- Replaced `vim.diagnostic.is_disabled()` with `vim.diagnostic.is_enabled()`.
- Removed nil check.
- Removed comment.
This requires Neovim 0.10.0: https://neovim.io/doc/user/news-0.10.html
> fix: vim.diagnostic.is_disabled() deprecation warning (deprecated in neovim 0.10.0)

- lua/bufferline/diagnostics.lua
- lua/bufferline/utils/init.lua
**Problem**
After rebuilding neovim from from `master` (specifically, `06135cc21571b2707121e31176f544a0e0901e1d`), I'm noticing the following deprecation warning on startup:
<details>
```
vim.tbl_add_reverse_lookup is deprecated. :help deprecated
stack traceback:
vim/shared.lua: in function 'tbl_add_reverse_lookup'
...nvim/lazy/bufferline.nvim/lua/bufferline/diagnostics.lua:10: in main chunk
[C]: in function 'require'
...are/nvim/lazy/bufferline.nvim/lua/bufferline/buffers.lua:8: in main chunk
[C]: in function 'require'
.../share/nvim/lazy/bufferline.nvim/lua/bufferline/lazy.lua:11: in function '__index'
...local/share/nvim/lazy/bufferline.nvim/lua/bufferline.lua:56: in function <...local/share/nvim/lazy/bufferline.nvim/lua/buffer
line.lua:54>
```
</details>
Looking at neovim's …
> Replace vim.tbl_add_reverse_lookup (deprecated in neovim v0.10)

- lua/bufferline/diagnostics.lua
As mentioned by @folke in https://github.com/akinsho/bufferline.nvim/pull/907#issuecomment-2119309364, #907 breaks backwards compat with Neovim 0.9.x.
- Add convenience function to hold the 0.10.0 and 0.9.x syntax for checking whether diagnostics are enabled or not.
> fix: maintain backwards compatibility with neovim 0.9.x

- lua/bufferline/ui.lua
- lua/bufferline/utils/init.lua
> fix: replace tbl_flatten to flatten():totable()

- lua/bufferline/utils/init.lua
Currently when checking if a buffer is valid, we use the function [nvim_buf_is_valid](https://neovim.io/doc/user/api.html#nvim_buf_is_valid()), however there is an edge case here described in the documentation where a buffer could have been unloaded, but still be "valid". If a buffer is unloaded and valid then referencing `buflisted` will result in a `(UNKNOWN PLUGIN): Error executing lua: attempt to call a number value` error.
Instead of `nvim_buf_is_valid` we use [nvim_buf_is_loaded](https://neovim.io/doc/user/api.html#nvim_buf_is_loaded()) which checks both whether a buffer is valid _and_ loaded. This way we never attempt to reference `buflisted` of unloaded or invalid buffers.
This PR should at least partially address #869. Applying the patch removes these errors for my config when …
> fix: don't reference unloaded buffers

- lua/bufferline/buffers.lua
- lua/bufferline/utils/init.lua
Currently when checking if a buffer is valid, we use the function [nvim_buf_is_valid](https://neovim.io/doc/user/api.html#nvim_buf_is_valid()), however there is an edge case here described in the documentation where a buffer could have been unloaded, but still be "valid". If a buffer is unloaded and valid then referencing `buf.buflisted` _could_ result in a `(UNKNOWN PLUGIN): Error executing lua: attempt to call a number value` error. I believe this issue may be a bug in Neovim itself and I have attempted to get more clarity on this [here](https://github.com/neovim/neovim/issues/10070#issuecomment-2180146301).
This issue reproduced in my config when `bufferline` attempted to reference the `buf.buflisted` property of unloaded `nvim-tree` buffer.
Note: A previous attempt at this fix (#928) …
> fix: UNKNOWN PLUGIN error resulting from unloaded buffers

- lua/bufferline/tabpages.lua
Hello,
I would like to use custom `separator_style` table for tabpages so I added the support in this fix.
> [!Note]
> The behavior still differs from buffers since tabpages don't use `ui.add_separators()`, `ui.get_separators()` or other `ui` functions
Thanks
> fix(tabs): use custom separator_style in tabpages

- doc/bufferline.txt
- lua/bufferline.lua
- lua/bufferline/config.lua
- lua/bufferline/diagnostics.lua
- lua/bufferline/types.lua
Closes #923.
This change makes the ui refresh whenever nvim reports a diagnostic change.
Demo: bufferline diagnostics are up to date
https://github.com/akinsho/bufferline.nvim/assets/29818440/9a9112ab-c210-4340-8be4-5fd89b46b75d
When nvim calls our diagnostic handler, we could get extra information about the change, for example the buffer that the change occurred in, all the details about the diagnostics in that buffer and options like `update_in_insert` (configured via `vim.diagnostic.config`). We could use these to replace `vim.diagnostic.get` call (possibly improving performance) and deprecate the bufferline option `diagnostic_update_in_insert`. However it would increase the complexity since we want to keep support for coc, so I decided not to do these changes.
> feat(diag): add `diagnostics_update_on_event` option

- doc/bufferline.txt
- lua/bufferline/models.lua
There seems to be no limitation to making `tabs` mode have access to `bufnr`.
> feat(tabpages): pass the bufnr to the `name_formatter`

- doc/bufferline.txt
Breakdown of https://github.com/akinsho/bufferline.nvim/pull/922. This PR fixes lua codes that cause runtime errors (a096678a84fe5e96e36ed7e817e80bf8a56e7740 and 5e7687afc9075a3213c9b7759f2bc63cab74ee12) and has buggy behaviours (9fedfd15a6bb4683dc894e8d8e4fa98489fea2fa), see the detailed commit message for more info.
These are mostly notes to myself how does it compare to previous PR:
- cherry-picked 698b202
- cherry-picked c0c9b72 without stylistic changes
- cherry-picked 8bd95fc without the extra print (currently on line 168 it doesn't have print buffer_a, on 486 it has)
Follow-up PRs (I might wait with these until this is merged to avoid merge conflicts):
cc @akinsho
> docs: fix broken/buggy lua examples

- README.md
- doc/bufferline.txt
Breakdown of #922.
Some nerdfonts symbols got removed, and some just had a different style (eg. filled vs hollow), I decided to go with filled. Github doesn't render nerdfonts symbols, here's how they look: (351763c)
cc @akinsho
> docs: nerdfonts symbols improvements

- doc/bufferline.txt
- lua/bufferline/config.lua
- lua/bufferline/pick.lua
I've added some new options to allow me to only use my homerow keys to switch between buffers. I think it might be interesting for other people too, so let me know if you're interested in merging it and/or if it needs any modifications. 
The default behavior is still the same.
> Allow different configuration for BufferLinePick

- lua/bufferline/utils/init.lua
We can set `show_buffer_icons` to false to disable web icons, but the icons is still being loaded during initialization. This is costly(loading the icon package needs ~ 20ms while the bufferline package itself cost just a few ms init time) and
unnecessary when user doesn't need the icons anyways. 
before `using :Lazy profile`
```
➜  bufferline.nvim 23.35ms
★  nvim-web-devicons 20.24ms
‒  nvim-web-devicons/plugin/nvim-web-devicons.vim 0.06ms
```
after
```
➜  bufferline.nvim 5.44ms
```
> Do not load web icons if not needed
